### PR TITLE
add anti Disconnect Google Colab

### PR DESCRIPTION
**Pull request by fskhri**

### CODE REVIEW

**Comment by SociallyIneptWeeb** [comment]
May I know what's the purpose of clicking the connect button at regular intervals?

**Comment by SociallyIneptWeeb** [comment]
It shouldn't disconnect, it will continue running as long as the cell is running and the tab is open

**Comment by fskhri** [comment]
oh, i see now

**Comment by SociallyIneptWeeb** [comment]
Feel free to close the pull request :)

**Pull request closed without merging**
